name: Bug Report
description: Please do not use bug reports for support issues or feature requests.
title: '[BUG]: '
labels: ['not-yet-viewed', 'bug']
assignees: 'Navino16'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR FEATURE REQUESTS!**
  - type: input
    id: version
    attributes:
      label: Version Number
      placeholder: eg. 1.16.0
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: What branch are you on?
      options:
        - main
        - develop
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Relevant Platform Definition
      description: >
        If you issue is happening with a specific platform please paste your platform definition here
        This will be automatically formatted into code, so no need for backticks.
      render: json
  - type: input
    id: logs
    attributes:
      label: Logs
      description: >
        Please share the relevant log file with the error on [Gist](https://gist.github.com).
      placeholder: "https://gist.github.com"
