name: Feature request
description: Submit new feature requests.
title: '[FEATURE]: '
labels: ['triage', 'enhancement']
assignees: 'Navino16'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR REPORT BUGS!**
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature.
    validations:
      required: true
