name: New public list
description: Ask for a new public list
title: '[LIST]: '
labels: ['not-yet-viewed', 'new-list']
assignees: 'Navino16'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR REPORT BUGS!**
  - type: dropdown
    id: platform
    attributes:
      label: Which platform are you looking for?
      options:
        - netflix
        - hbo
        - disney
        - amazon
        - amazon-prime
        - apple-tv
        - chili
        - freevee
        - google
        - hulu
        - itunes
        - osn
        - paramount-plus
        - rakuten-tv
        - shahid
        - star-plus
        - starz
        - viaplay
        - vudu
    validations:
      required: true
  - type: dropdown
    id: location
    attributes:
      label: From where the top10 should be taken?
      options:
        - world
        - afghanistan
        - albania
        - algeria
        - andorra
        - angola
        - antigua-and-barbuda
        - argentina
        - armenia
        - australia
        - austria
        - azerbaijan
        - bahamas
        - bahrain
        - bangladesh
        - barbados
        - belarus
        - belgium
        - belize
        - benin
        - bhutan
        - bolivia
        - bosnia-and-herzegovina
        - botswana
        - brazil
        - brunei
        - bulgaria
        - burkina-faso
        - burundi
        - cambodia
        - cameroon
        - canada
        - cape-verde
        - central-african-republic
        - chad
        - chile
        - china
        - colombia
        - comoros
        - costa-rica
        - croatia
        - cyprus
        - czech-republic
        - democratic-republic-of-the-congo
        - denmark
        - djibouti
        - dominica
        - dominican-republic
        - east-timor
        - ecuador
        - egypt
        - equatorial-guinea
        - eritrea
        - estonia
        - ethiopia
        - fiji
        - finland
        - france
        - gabon
        - gambia
        - georgia
        - germany
        - ghana
        - greece
        - grenada
        - guadeloupe
        - guatemala
        - guinea
        - guinea-bissau
        - guyana
        - haiti
        - honduras
        - hong-kong
        - hungary
        - iceland
        - india
        - indonesia
        - iraq
        - ireland
        - israel
        - italy
        - ivory-coast
        - jamaica
        - japan
        - jordan
        - kazakhstan
        - kenya
        - kiribati
        - kosovo
        - kuwait
        - kyrgyzstan
        - laos
        - latvia
        - lebanon
        - lesotho
        - liberia
        - libya
        - liechtenstein
        - lithuania
        - luxembourg
        - madagascar
        - malawi
        - malaysia
        - maldives
        - mali
        - malta
        - marshall-islands
        - martinique
        - mauritania
        - mauritius
        - mexico
        - micronesia
        - moldova
        - monaco
        - mongolia
        - montenegro
        - morocco
        - mozambique
        - myanmar
        - namibia
        - nauru
        - nepal
        - netherlands
        - new-caledonia
        - new-zealand
        - nicaragua
        - niger
        - nigeria
        - north-macedonia
        - norway
        - oman
        - pakistan
        - palau
        - palestine
        - panama
        - papua-new-guinea
        - paraguay
        - peru
        - philippines
        - poland
        - portugal
        - qatar
        - republic-of-the-congo
        - reunion
        - romania
        - russia
        - rwanda
        - saint-kitts-and-nevis
        - saint-lucia
        - saint-vincent-and-the-grenadines
        - salvador
        - samoa
        - san-marino
        - sao-tome-and-principe
        - saudi-arabia
        - senegal
        - serbia
        - seychelles
        - sierra-leone
        - singapore
        - slovakia
        - slovenia
        - solomon-islands
        - somalia
        - south-africa
        - south-korea
        - south-sudan
        - spain
        - sri-lanka
        - sudan
        - suriname
        - swaziland
        - sweden
        - switzerland
        - taiwan
        - tajikistan
        - tanzania
        - thailand
        - togo
        - tonga
        - trinidad-and-tobago
        - tunisia
        - turkey
        - turkmenistan
        - tuvalu
        - uganda
        - ukraine
        - united-arab-emirates
        - united-kingdom
        - united-states
        - uruguay
        - uzbekistan
        - vanuatu
        - vatican-city
        - venezuela
        - vietnam
        - yemen
        - zambia
        - zimbabwe
    validations:
      required: true
  - type: dropdown
    id: fallback
    attributes:
      label: Do you want any fallback in case of nothing found for your desired location?
      options:
        - world
        - afghanistan
        - albania
        - algeria
        - andorra
        - angola
        - antigua-and-barbuda
        - argentina
        - armenia
        - australia
        - austria
        - azerbaijan
        - bahamas
        - bahrain
        - bangladesh
        - barbados
        - belarus
        - belgium
        - belize
        - benin
        - bhutan
        - bolivia
        - bosnia-and-herzegovina
        - botswana
        - brazil
        - brunei
        - bulgaria
        - burkina-faso
        - burundi
        - cambodia
        - cameroon
        - canada
        - cape-verde
        - central-african-republic
        - chad
        - chile
        - china
        - colombia
        - comoros
        - costa-rica
        - croatia
        - cyprus
        - czech-republic
        - democratic-republic-of-the-congo
        - denmark
        - djibouti
        - dominica
        - dominican-republic
        - east-timor
        - ecuador
        - egypt
        - equatorial-guinea
        - eritrea
        - estonia
        - ethiopia
        - fiji
        - finland
        - france
        - gabon
        - gambia
        - georgia
        - germany
        - ghana
        - greece
        - grenada
        - guadeloupe
        - guatemala
        - guinea
        - guinea-bissau
        - guyana
        - haiti
        - honduras
        - hong-kong
        - hungary
        - iceland
        - india
        - indonesia
        - iraq
        - ireland
        - israel
        - italy
        - ivory-coast
        - jamaica
        - japan
        - jordan
        - kazakhstan
        - kenya
        - kiribati
        - kosovo
        - kuwait
        - kyrgyzstan
        - laos
        - latvia
        - lebanon
        - lesotho
        - liberia
        - libya
        - liechtenstein
        - lithuania
        - luxembourg
        - madagascar
        - malawi
        - malaysia
        - maldives
        - mali
        - malta
        - marshall-islands
        - martinique
        - mauritania
        - mauritius
        - mexico
        - micronesia
        - moldova
        - monaco
        - mongolia
        - montenegro
        - morocco
        - mozambique
        - myanmar
        - namibia
        - nauru
        - nepal
        - netherlands
        - new-caledonia
        - new-zealand
        - nicaragua
        - niger
        - nigeria
        - north-macedonia
        - norway
        - oman
        - pakistan
        - palau
        - palestine
        - panama
        - papua-new-guinea
        - paraguay
        - peru
        - philippines
        - poland
        - portugal
        - qatar
        - republic-of-the-congo
        - reunion
        - romania
        - russia
        - rwanda
        - saint-kitts-and-nevis
        - saint-lucia
        - saint-vincent-and-the-grenadines
        - salvador
        - samoa
        - san-marino
        - sao-tome-and-principe
        - saudi-arabia
        - senegal
        - serbia
        - seychelles
        - sierra-leone
        - singapore
        - slovakia
        - slovenia
        - solomon-islands
        - somalia
        - south-africa
        - south-korea
        - south-sudan
        - spain
        - sri-lanka
        - sudan
        - suriname
        - swaziland
        - sweden
        - switzerland
        - taiwan
        - tajikistan
        - tanzania
        - thailand
        - togo
        - tonga
        - trinidad-and-tobago
        - tunisia
        - turkey
        - turkmenistan
        - tuvalu
        - uganda
        - ukraine
        - united-arab-emirates
        - united-kingdom
        - united-states
        - uruguay
        - uzbekistan
        - vanuatu
        - vatican-city
        - venezuela
        - vietnam
        - yemen
        - zambia
        - zimbabwe
